app/merchants/__init__.py
from flask import Blueprint

merchant = Blueprint('merchant', __name__, url_prefix='/merchants')

from app.merchants import views

app/merchants/views.py
from flask import render_template, flash, redirect, url_for, request
from app.merchants import merchant
from app.models import merchants, wares, products
from app import dbase
from string import capwords

@merchant.route('/')
def all():
    allData = merchants.query.all()

    return render_template('merchants.html', merchants=allData)

#   CRUD System for all merchants   #
@merchant.route('/insert', methods=["POST", "GET"])
def allInsert():
    if request.method == "POST":
        name = capwords(request.form['name'])
        type = request.form['type'].capitalize()
        location = request.form['location'].capitalize()

        merchant = merchants(name, type, location)
        dbase.session.add(merchant)
        dbase.session.commit()
        flash('Merchant Register Successful')

        return redirect(url_for('merchant.all'))

@merchant.route('/update', methods=['POST', 'GET'])
def allUpdate():
    if request.method == "POST":
        merchant = merchants.query.get(request.form.get('id'))

        merchant.name = capwords(request.form['name'])
        merchant.type = request.form['type'].capitalize()
        merchant.location = request.form['location'].capitalize()

        dbase.session.commit()
        flash('Merchant Update Successful')

        return redirect(url_for('merchant.all'))

@merchant.route('/delete/<id>', methods=['POST', 'GET'])
def allDelete(id):
    merchant = merchants.query.get(id)
    
    dbase.session.delete(merchant)
    dbase.session.commit()
    flash('Merchant Deleted Successfully')

    return redirect(url_for('merchant.all'))

#   Merchants in Monstadt   #
@merchant.route('/mondstadt')
def mondstadt():
    allData = merchants.query.filter_by(location="Mondstadt").all()

    return render_template('mondstadt.html', merchants=allData)

@merchant.route('/mondstadt/<name>/wares', methods=['POST', 'GET'])
def mondstadtWares(name):
    merchantData = merchants.query.filter_by(name=name).first()
    allProducts = products.query.all()
    allData = wares.query.join(merchants, wares.merchantID == merchants.id).join(products, wares.productID == products.id).add_columns(products.itemName, wares.stock, wares.price, wares.productID, merchants.name, wares.ID, merchants.location, merchants.id).filter(wares.merchantID==merchantData.id).order_by(wares.price.asc())

    return render_template('wares.html', wares=allData, merchant=merchantData, allProducts=allProducts)

#   CRUD for Mondstadt   #
@merchant.route('/mondstadt/insert', methods=["POST", "GET"])
def mondstadtInsert():
    if request.method == "POST":
        name = capwords(request.form['name'])
        type = request.form['type'].capitalize()
        location = request.form['location'].capitalize()

        merchant = merchants(name, type, location)
        dbase.session.add(merchant)
        dbase.session.commit()
        flash('Merchant Register Successful')

        return redirect(url_for('merchant.mondstadt'))

@merchant.route('/monstadt/update', methods=['POST', 'GET'])
def mondstadtUpdate():
    if request.method == "POST":
        merchant = merchants.query.get(request.form.get('id'))

        merchant.name = capwords(request.form['name'])
        merchant.type = request.form['type'].capitalize()
        merchant.location = request.form['location'].capitalize()

        dbase.session.commit()
        flash('Merchant Update Successful')

        return redirect(url_for('merchant.mondstadt'))

@merchant.route('/mondstadt/delete/<id>', methods=['POST', 'GET'])
def mondstadtDelete(id):
    merchant = merchants.query.get(id)
    
    dbase.session.delete(merchant)
    dbase.session.commit()
    flash('Merchant Deleted Successfully')

    return redirect(url_for('merchant.mondstadt'))

#   Merchants in Liyue   #
@merchant.route('/liyue')
def liyue():
    allData = merchants.query.filter_by(location="liyue").all()

    return render_template('liyue.html', merchants=allData)

@merchant.route('/liyue/<name>/wares', methods=['POST', 'GET'])
def liyueWares(name):
    merchantData = merchants.query.filter_by(name=name).first()
    allProducts = products.query.all()
    allData = wares.query.join(merchants, wares.merchantID == merchants.id).join(products, wares.productID == products.id).add_columns(products.itemName, wares.stock, wares.price, wares.productID, merchants.id, wares.ID, merchants.location, merchants.name).filter(wares.merchantID==merchantData.id).order_by(wares.price.asc())

    return render_template('wares.html', wares=allData, merchant=merchantData, allProducts=allProducts)

#   CRUD for Liyue   #
@merchant.route('/liyue/insert', methods=["POST", "GET"])
def liyueInsert():
    if request.method == "POST":
        name = capwords(request.form['name'])
        type = request.form['type'].capitalize()
        location = request.form['location'].capitalize()

        merchant = merchants(name, type, location)
        dbase.session.add(merchant)
        dbase.session.commit()
        flash('Merchant Register Successful')

        return redirect(url_for('merchant.liyue'))

@merchant.route('/liyue/update', methods=['POST', 'GET'])
def liyueUpdate():
    if request.method == "POST":
        merchant = merchants.query.get(request.form.get('id'))

        merchant.name = capwords(request.form['name'])
        merchant.type = request.form['type'].capitalize()
        merchant.location = request.form['location'].capitalize()

        dbase.session.commit()
        flash('Merchant Update Successful')

        return redirect(url_for('merchant.liyue'))

@merchant.route('/liyue/delete/<id>', methods=['POST', 'GET'])
def liyueDelete(id):
    merchant = merchants.query.get(id)
    
    dbase.session.delete(merchant)
    dbase.session.commit()
    flash('Merchant Deleted Successfully')

    return redirect(url_for('merchant.liyue'))

#   CRUD FOR WARES   #
@merchant.route('/wares/update', methods=['POST'])
def wareUpdate():
    if request.method == 'POST':
        ware = wares.query.get(request.form.get('ID'))
        merchantName = request.form['merchantName']
        location = request.form['location'].lower()

        ware.merchantID = request.form['mID']
        ware.productID = request.form['pID']
        ware.stock = request.form['stock']
        ware.price = request.form['price']

        dbase.session.commit()
        flash('Ware Update Successful')

        return redirect(f'/merchants/{location}/{merchantName}/wares')

@merchant.route('/<location>/<name>/wares/delete/<id>')
def wareDelete(id, name, location):
    ware = wares.query.get(id)

    dbase.session.delete(ware)
    dbase.session.commit()
    flash('Ware Deleted Successfully')

    return redirect(f'/merchants/{location}/{name}/wares')

@merchant.route('/wares/insert', methods=['POST'])
def wareInsert():
    location = request.form['location'].lower()
    merchantName = request.form['merchantName']
    if request.method == 'POST':
        merchantID = request.form['merchantID']
        productID = request.form['item']
        stock = request.form['stock']
        price = request.form['price']

        ware = wares(merchantID, productID, stock, price)
        dbase.session.add(ware)
        dbase.session.commit()
        flash('Ware Register Successful')

        return redirect(f'/merchants/{location}/{merchantName}/wares')

app/templates/error404.html
{% extends 'layout.html' %}

{% block title %}
    Error 404
{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Error 404: Page Not Found</h1>
    </div>
{% endblock content %}

app/templates/error500.html
{% extends 'layout.html' %}

{% block title %}
    Error 500
{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Error 500: Internal Server Error</h1>
    </div>
{% endblock content %}

app/templates/liyue.html
{% extends 'layout.html' %}

{% block title %}
    GenshInventory Liyue
{% endblock title %}

{% block content %}
    <div class="jumbotron p-3">
        <div class="well text-center">
            <h4 class="display-4">Liyue Merchants</h1>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-12">
                <div class="jumbotron p-3">
                    <h2>Manage <b>Liyue Merchants</b>
                        <button type="button" class="btn btn-outline-success float-right" data-toggle="modal" data-target="#modaladd">ADD MERCHANT</button>
                    </h2>
                    <div class="container-fluid text-center">
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            <span class="sr-only">Close</span>
                                        </button>
                                        <strong>{{message}}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>

                    <!--TABLE-->
                    <table class="table table-hover">
                        <tr style="text-align:center; background-color:darkgray">
                            <th>Name</th>
                            <th>Type</th>
                            <th>Location</th>
                            <th>Action</th>
                        </tr>

                        {% for row in merchants %}
                        <tr style="text-align: center; background-color:rgb(43, 43, 43); color:white">
                            <th>{{row.name}}</th>
                            <th>{{row.type}}</th>
                            <th>{{row.location}}</th>
                            <th>
                                <a href="/merchants/liyue/{{row.name}}/wares" class="btn btn-primary" role="button">CHECK WARES</a>
                                <a href="/merchants/liyue/update/{{row.id}}" class="btn btn-warning" data-toggle="modal" data-target="#modaledit{{row.id}}">EDIT</a>
                                <a href="/merchants/liyue/delete/{{row.id}}" class="btn btn-danger" onclick="return confirm('Confirm Delete')">DELETE</a>
                            </th>
                        </tr>

                        <!--MODAL EDIT-->
                        <div id="modaledit{{row.id}}" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Update Merchant</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{url_for('merchant.liyueUpdate')}}" method="POST">
                                            <div class="form-group">
                                                <label><b>Name</b></label>
                                                <input type="hidden" name="id" value="{{row.id}}">
                                                <input type="text" class="form-control" name="name" required="1" value="{{row.name}}">
                                            </div>
                                            <div class="form-group">
                                                <label><b>Type</b></label>
                                                <input type="hidden" name="location" value="Liyue">
                                                <input type="text" class="form-control" name="type" required="1" value="{{row.type}}">
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary" type="submit">Update</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        {% endfor %}

                    </table>
                </div>

                <!--MODAL ADD-->
                <div id="modaladd" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Add Merchant</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('merchant.liyueInsert')}}" method="POST">
                                    <div class="form-group">
                                        <label><b>Name</b></label>
                                        <input type="text" class="form-control" name="name" required="1">
                                    </div>
                                    <div class="form-group">
                                        <label><b>Type</b></label>
                                        <input type="text" class="form-control" name="type" required="1">
                                        <input type="hidden" name="location" value="Liyue">
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Add</button>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock content %}

app/templates/merchants.html
{% extends 'layout.html' %}

{% block title %}
    GenshInventory Merchants
{% endblock title %}

{% block content %}
    <div class="jumbotron p-3">
        <div class="well text-center">
            <h4 class="display-4">Merchants</h1>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-12">
                <div class="jumbotron p-3">
                    <h2>Manage <b>Merchants</b>
                        <button type="button" class="btn btn-outline-success float-right" data-toggle="modal" data-target="#modaladd">ADD MERCHANT</button>
                    </h2>
                    <div class="container-fluid text-center">
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            <span class="sr-only">Close</span>
                                        </button>
                                        <strong>{{message}}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>

                    <!--TABLE-->
                    <table class="table table-hover">
                        <tr style="text-align:center; background-color:darkgray">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Location</th>
                            <th>Action</th>
                        </tr>

                        {% for row in merchants %}
                        <tr style="text-align: center; background-color:rgb(43, 43, 43); color:white">
                            <th>{{row.id}}</th>
                            <th>{{row.name}}</th>
                            <th>{{row.type}}</th>
                            <th>{{row.location}}</th>
                            <th>
                                {% if row.location == 'Mondstadt' %}
                                    <a href="/merchants/mondstadt/{{row.name}}/wares" class="btn btn-primary" role="button">CHECK WARES</a>
                                {% else %}
                                    <a href="/merchants/liyue/{{row.name}}/wares" class="btn btn-primary" role="button">CHECK WARES</a>
                                {% endif %}
                                <a href="/merchants/update/{{row.id}}" class="btn btn-warning" data-toggle="modal" data-target="#modaledit{{row.id}}">EDIT</a>
                                <a href="/merchants/delete/{{row.id}}" class="btn btn-danger" onclick="return confirm('Confirm Delete')">DELETE</a>
                            </th>
                        </tr>

                        <!--MODAL EDIT-->
                        <div id="modaledit{{row.id}}" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Update Merchant</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{url_for('merchant.allUpdate')}}" method="POST">
                                            <div class="form-group">
                                                <label><b>Name</b></label>
                                                <input type="hidden" name="id" value="{{row.id}}">
                                                <input type="text" class="form-control" name="name" required="1" value="{{row.name}}">
                                            </div>
                                            <div class="form-group">
                                                <label><b>Type</b></label>
                                                <input type="text" class="form-control" name="type" required="1" value="{{row.type}}">
                                            </div>
                                            <div class="form-group">
                                                <label><b>Location</b></label>
                                                <select name="location" class="form-control">
                                                    <option value="Mondstadt">Mondstadt</option>
                                                    <option value="Liyue">Liyue</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary" type="submit">Update</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </table>
                </div>

                <!--MODAL ADD-->
                <div id="modaladd" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Add Merchant</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('merchant.allInsert')}}" method="POST">
                                    <div class="form-group">
                                        <label><b>Name</b></label>
                                        <input type="text" class="form-control" name="name" required="1">
                                    </div>
                                    <div class="form-group">
                                        <label><b>Type</b></label>
                                        <input type="text" class="form-control" name="type" required="1">
                                    </div>
                                    <div class="form-group">
                                        <label><b>Location</b></label>
                                        <select name="location" class="form-control">
                                            <option value="Mondstadt">Mondstadt</option>
                                            <option value="Liyue">Liyue</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Add</button>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

app/templates/mondstadt.html
{% extends 'layout.html' %}

{% block title %}
    GenshInventory Monstadt
{% endblock title %}

{% block content %}
    <div class="jumbotron p-3">
        <div class="well text-center">
            <h4 class="display-4">Mondstadt Merchants</h1>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-12">
                <div class="jumbotron p-3">
                    <h2>Manage <b>Mondstadt Merchants</b>
                        <button type="button" class="btn btn-outline-success float-right" data-toggle="modal" data-target="#modaladd">ADD MERCHANT</button>
                    </h2>
                    <div class="container-fluid text-center">
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            <span class="sr-only">Close</span>
                                        </button>
                                        <strong>{{message}}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>

                    <!--TABLE-->
                    <table class="table table-hover">
                        <tr style="text-align:center; background-color:darkgray">
                            <th>Name</th>
                            <th>Type</th>
                            <th>Location</th>
                            <th>Action</th>
                        </tr>

                        {% for row in merchants %}
                        <tr style="text-align: center; background-color:rgb(43, 43, 43); color:white">
                            <th>{{row.name}}</th>
                            <th>{{row.type}}</th>
                            <th>{{row.location}}</th>
                            <th>
                                <a href="/merchants/mondstadt/{{row.name}}/wares" class="btn btn-primary" role="button">CHECK WARES</a>
                                <a href="/merchants/mondstadt/update/{{row.id}}" class="btn btn-warning" data-toggle="modal" data-target="#modaledit{{row.id}}">EDIT</a>
                                <a href="/merchants/mondstadt/delete/{{row.id}}" class="btn btn-danger" onclick="return confirm('Confirm Delete')">DELETE</a>
                            </th>
                        </tr>

                        <!--MODAL EDIT-->
                        <div id="modaledit{{row.id}}" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Update Merchant</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{url_for('merchant.mondstadtUpdate')}}" method="POST">
                                            <div class="form-group">
                                                <label><b>Name</b></label>
                                                <input type="hidden" name="id" value="{{row.id}}">
                                                <input type="text" class="form-control" name="name" required="1" value="{{row.name}}">
                                            </div>
                                            <div class="form-group">
                                                <label><b>Type</b></label>
                                                <input type="hidden" name="location" value="Mondstadt">
                                                <input type="text" class="form-control" name="type" required="1" value="{{row.type}}">
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary" type="submit">Update</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        {% endfor %}

                    </table>
                </div>

                <!--MODAL ADD-->
                <div id="modaladd" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Add Merchant</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('merchant.mondstadtInsert')}}" method="POST">
                                    <div class="form-group">
                                        <label><b>Name</b></label>
                                        <input type="text" class="form-control" name="name" required="1">
                                    </div>
                                    <div class="form-group">
                                        <label><b>Type</b></label>
                                        <input type="text" class="form-control" name="type" required="1">
                                        <input type="hidden" name="location" value="Mondstadt">
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Add</button>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock content %}